swagger: "2.0"
info:
  title: Todo API
  version: "1.0.0"
schemes:
  - http
  - https
paths:
  /tasks/fetch:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks from the database.
      security:
        - apiKey: []
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Task"
        500:
          description: Internal Server Error

  /tasks/addTask:
    post:
      summary: Add a task
      description: Add a new task to the todo list.
      security:
        - apiKey: []
      parameters:
        - in: body
          name: task
          description: Task object
          required: true
          schema:
            $ref: "#/definitions/Task"  # Use the Task model here
      responses:
        201:
          description: Task added successfully
        400:
          description: Bad Request - Invalid input
        500:
          description: Internal Server Error

  /tasks/restoreTask:
    post:
      summary: Restore a task by ID
      description: Restore a task from the todo list by its ID.
      security:
        - apiKey: []
      parameters:
        - in: body
          name: restore
          description: Task restoration object
          required: true
          schema:
            $ref: "#/definitions/RestoreRequest"
      responses:
        201:
          description: Task restored successfully
        400:
          description: Bad Request - Invalid input
        500:
          description: Internal Server Error

  /tasks/deleteTask/{id}:
    delete:
      summary: Soft Delete a task by ID
      description: Soft Delete a task from the todo list by its ID.
      security:
        - apiKey: []
      parameters:
        - in: path
          name: id
          description: ID of the task to delete
          required: true
          type: integer
      responses:
        200:
          description: Task soft deleted successfully
        404:
          description: Task not found
        400:
          description: Bad Request - Invalid input
        500:
          description: Internal Server Error

  /tasks/completeTask/{id}:
    put:
      summary: Mark a task as complete
      description: Mark a task from the todo list as complete by its ID.
      security:
        - apiKey: []
      parameters:
        - in: path
          name: id
          description: ID of the task to mark as complete
          required: true
          type: integer
      responses:
        200:
          description: Task marked as complete successfully
        404:
          description: Task not found
        400:
          description: Bad Request - Invalid input
        500:
          description: Internal Server Error
          
  # /tasks/restoreTask/{id}:
  #   put:
  #     summary: Restore a soft-deleted task by setting isDeleted to false.
  #     description: Restore a soft-deleted a task from the todo list by its ID.
  #     security:
  #       - apiKey: []
  #     parameters:
  #       - in: path
  #         name: id
  #         description: The ID of the soft-deleted task to be restored.
  #         required: true
  #         type: integer          
  #     responses:
  #       200:
  #         description: Task restored successfully.
  #       404:
  #         description: Soft-deleted task not found.
  #       400:
  #         description: Bad request. Task ID is required.
  #       500:
  #         description: Internal Server Error.

definitions:
  Task:
    type: object
    properties:
      id:
        type: integer
        description: Task ID
      tasks:
        type: string
        description: Task description
      complete:
        type: boolean
        description: Task completion status (true for complete, false for incomplete

  RestoreRequest:
    type: object
    properties:
      taskId:
        type: integer
        description: Task ID

securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-KEY

security:
  - apiKey: []
